# Generated by Django 2.1.3 on 2018-11-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('c_password', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=20)),
                ('phoneno', models.CharField(max_length=100)),
            ],
        ),
    ]
