# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20181106_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='active',
        ),
    ]
