# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20181106_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30, unique=True)),
                ('receiver', models.CharField(max_length=30, unique=True)),
                ('message', models.CharField(max_length=100000)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
