# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='receiver',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.CharField(max_length=30),
        ),
    ]
