# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20181124_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='time',
            field=models.CharField(default=0.0, max_length=20),
        ),
    ]
