# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_messages_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=30, unique=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Users')),
            ],
        ),
    ]
