# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_userlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlinks',
            name='users',
            field=models.CharField(max_length=30),
        ),
    ]
