# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20181125_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlinks',
            name='link',
        ),
        migrations.AddField(
            model_name='userlinks',
            name='link',
            field=models.ManyToManyField(to='register.Users'),
        ),
    ]
