# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20181127_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlinks',
            name='link',
        ),
        migrations.DeleteModel(
            name='Userlinks',
        ),
    ]
