# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_users_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_time',
            field=models.DateTimeField(default=b'0'),
        ),
    ]
