# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_auto_20181128_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_time',
            field=models.DateTimeField(default=True),
        ),
    ]
