# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_remove_messages_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='date_time',
            field=models.DateTimeField(default=0),
        ),
    ]
