# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0028_users_pppp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pppp',
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
